config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "accounts#index"
  resources :accounts, except: [:delete] do
    resources :activities, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :categories, except: [:show, :delete]

  resources :merchants, only: [] do
    get 'autocomplete', on: :collection
  end

end

app/models/activity.rb
class Activity < ApplicationRecord
  include ElasticsearchActivity

  after_commit -> { __elasticsearch__.index_document }, on: [:create, :update]
  after_commit -> { __elasticsearch__.delete_document }, on: :destroy

  belongs_to :account
  belongs_to :category

  def self.merchant_autocomplete(args)
    if args[:term].present?
      request = {
        query: {
          match: { merchant: args[:term] }
        },
        _source: :merchant
      }

      response = Activity.search(request)

      response.per(5).results.map(&:_source).map(&:merchant)
    else
      []
    end
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def new
    @account = Account.find(params[:account_id])
    @activity = @account.activities.new
  end

  def create
    @account = Account.find(params[:account_id])
    @activity = @account.activities.new(activity_params)

    if @activity.save
      sleep(1)
      redirect_to account_path(@account), notice: "Activity on #{@activity.transaction_date} for #{@activity.amount} sucessfully added to account"
    else
      flash.now[:error] = "Something went wrong"
      render :new
    end
  end

  def edit
    @account = Account.find(params[:account_id])
    @activity = @account.activities.find(params[:id])
  end

  def update
    @account = Account.find(params[:account_id])
    @activity = @account.activities.find(params[:id])
    if @activity.update(activity_params)
      sleep(1)
      redirect_to account_path(@account), notice: "Activity on #{@activity.transaction_date} for #{@activity.amount} sucessfully updated"
    else
      flash.now[:error] = "Something went wrong"
      render :edit
    end
  end

  def destroy
    @account = Account.find(params[:account_id])
    @activity = @account.activities.find(params[:id])

    if @activity.destroy
      sleep(1)
      redirect_to account_path(@account), notice: "Activity on #{@activity.transaction_date} for #{@activity.amount} sucessfully deleted"
    end
  end

  private

  def activity_params
    params.require(:activity).permit(
      :account_id,
      :transaction_date,
      :merchant,
      :description,
      :cleared,
      :category_id,
      :amount
    )
  end
end

app/views/activities/_form.html.erb
<%= simple_form_for [@account, @activity] do |f| %>
  <%= f.input :account_id, collection: Account.all, prompt: "Select Account", selected: @activity.account_id %>
  <%= f.input :transaction_date, order: [:month, :day, :year] %>
  <%= f.input :merchant, url: autocomplete_merchants_path, as: :autocomplete  %>
  <%= f.input :category_id, collection: Category.all, prompt: "Select Category", selected: @activity.category_id %>
  <%= f.input :description %>
  <%= f.input :amount, as: :currency %>
  <%= f.input :cleared, input_html: { checked: @activity.cleared.nil? ? true : @activity.cleared } %>
  <%= f.button :submit, class: "btn btn-outline-primary" %>
<% end %>

app/views/activities/edit.html.erb
<div class="container">
  <div class="page-header">
    <h1>Edit Activity</h1>
  </div>
  
  <%= render 'form' %>
</div>

app/views/activities/new.html.erb
<div class="container">
  <div class="page-header">
    <h1>New Activity</h1>
  </div>
  
  <%= render 'form' %>
</div>