config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "accounts#index"
  resources :accounts, except: [:delete] do
    resources :activities, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :categories, except: [:show, :delete]

  resources :merchants, only: [] do
    get 'autocomplete', on: :collection
  end

end

app/views/layouts/_nav.html.erb
<ul class="nav nav-pills nav-justified">
  <li class="nav-item">
    <%= link_to "Accounts Overview", accounts_path, class: "nav-link #{active_tab?(accounts_path) || active_tab?(root_path)}" %>
  </li>
  <% accounts.each do |account| %>
    <li class="nav-item">
      <%= link_to "#{account.name}", account_path(account), class: "nav-link #{active_tab?(account_path(account))}" %>
    </li>
  <% end %>
  <li class="nav-item">
    <%= link_to "Categories", categories_path, class: "nav-link #{active_tab?(categories_path)}" %>
  </li>
</ul>

app/views/layouts/_pagination.html.erb
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-end">
    <li class="page-item <%= "#{resp.first_page? ? "disabled" : ""}" %>">
      <%= link_to "Previous", account_path(account, page: resp.prev_page), class: "page-link" %>
    </li>
    <% (1..resp.total_pages).each do |page| %>
      <li class="page-item <%= active_page?(current_page: resp.current_page, page: page) %>">
        <%= link_to page, account_path(account, page: page), class: "page-link" %></a>
      </li>
    <% end %>
    <li class="page-item <%= "#{resp.last_page? ? "disabled" : ""}" %>">
      <%= link_to "Next", account_path(account, page: resp.next_page), class: "page-link" %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpensesTrackerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <% if flash[:error] %>
      <div class="alert alert-danger" role="alert">
        <%= flash[:error] %>
      </div>
    <% end %>
    <% if flash[:notice] %>
      <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>