config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "accounts#index"
  resources :accounts, except: [:delete] do
    resources :activities, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :categories, except: [:show, :delete]

  resources :merchants, only: [] do
    get 'autocomplete', on: :collection
  end

end

app/models/account.rb
class Account < ApplicationRecord
  has_many :activities

  after_commit :update_activity_documents, on: :update

  ACCOUNT_TYPES = ["Checking", "Credit Card"]

  validates :account_type, inclusion:{ in: ACCOUNT_TYPES, message: "%{value} is not a valid account_type" }

  def update_activity_documents
    if activities.size > 0
      Activity.bulk_update_activity_documents(
        activity_ids: activities.pluck(:id),
        data: { account: AccountSerializer.new(self).as_json }
      )
    end
  end

  def get_activities(args={})
    page = args[:page] || 1

    response = Activity.search({
      query: {
        bool: {
          filter: [ { term: { "account.id" => self.id } } ]
        }
      },
      sort: [{ transaction_date: :desc } ],
      aggs: {
        total_balance: {
          sum: { field: :amount }
        }
      }
    })

    response.page(page).per(25)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
  end

  def show
    @account = Account.find(params[:id])

    @response = @account.get_activities(page: params[:page])

    @activities = @response.results.map(&:_source)
    @total_balance = @response.aggregations.total_balance.value
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)

    if @account.save
      redirect_to accounts_path, notice: "#{@account.name} was successfully added to your accounts"
    else
      flash.now[:error] = "Something went wrong"
      render :new
    end
  end

  def edit
    @account = Account.find(params[:id])
  end

  def update
    @account = Account.find(params[:id])
    if @account.update(account_params)
      redirect_to accounts_path, notice: "#{@account.name} was successfully updated"
    else
      flash.now[:error] = "Something went wrong"
      render :edit
    end
  end

  private

  def account_params
    params.require(:account).permit(:name, :account_type, :enabled, :credit_limit)
  end
end

app/views/accounts/_form.erb
<%= simple_form_for @account do |f| %>
  <%= f.input :name %>
  <%= f.input :account_type, collection: Account::ACCOUNT_TYPES, selected: @account.account_type, prompt: "Select Account Type" %>
  <%= f.input :credit_limit, as: :currency %>
  <%= f.input :enabled, input_html: { checked: @account.enabled.nil? ? true : @account.enabled } %>
  <%= f.button :submit, class: "btn btn-outline-primary" %>
<% end %>

app/views/accounts/edit.erb
<div class="container">
  <div class="page-header">
    <h1>Edit Account</h1>
  </div>
  
  <%= render 'form' %>
</div>

app/views/accounts/index.erb
<div class="container">
  <div class="page-header">
    <div class="float-right">
      <%= link_to "Add new account", new_account_path, class: "btn btn-outline-primary" %>
    </div>
    <h1>Accounts</h1>
  </div>

    <% accounts.group_by(&:account_type).each do |type, grouped_accounts| %>
      <h5><%= type %></h5>

      <% grouped_accounts.each do |account| %>
        <ul class="list-group">
          <li class="list-group-item">
            <%= account.name %> 
            <span>
              <%= link_to edit_account_path(account) do %>
                <%= fa_icon 'edit', alt: "edit account" %>
              <% end %>
            </span>
          </li>
        </ul>
      <% end %>

    <% end %>
  
</div>

app/views/accounts/new.erb
<div class="container">
  <div class="page-header">
    <h1>New Account</h1>
  </div>
  
  <%= render 'form' %>
</div>

app/views/accounts/show.html.erb
<div class="card">
  <div class="card-body">
    <%= link_to "Add Activity", new_account_activity_path(@account), class: "btn btn-outline-primary btn-lg float-right" %>
    <h5 class="card-title">Current Balance: <%= number_to_currency(@total_balance) %></h5>
    <% if @account.credit_limit %>
      <h6 class="card-subtitle mb-2 text-muted">Remaining Credit: <%= number_to_currency(@account.credit_limit - @total_balance) %></h6>
    <% end %>

  </div>
</div>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Merchant and Description</th>
      <th scope="col">Category</th>
      <th scope="col">Amount</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @activities.each do |activity| %>
      <tr class='<%= activity.cleared ? 'cleared' : 'not-cleared' %>'>
        <th scope="row"><%= activity.transaction_date %></th>
        <td>
          <%= activity.merchant %>
            <% if activity.description.present? %>
              <span>-- <%= activity.description %></span>
            <% end %>
        </td>
        <td><%= activity.category.name %></td>
        <td><%= number_to_currency(activity.amount) %></td>
        <td>
          <%= link_to edit_account_activity_path(@account, activity.id) do %>
            <%= fa_icon 'edit', alt: "edit activity" %>
          <% end %>
          <%= link_to account_activity_path(@account, activity.id), method: :delete, data: {confirm: "Are you sure you want to delete this activity?"} do %>
            <%= fa_icon 'trash  ', alt: "delete activity" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'layouts/pagination', account: @account, resp: @response %>